baseURL = 'https://em-baggie.github.io/'
languageCode = 'en-us'
title = 'Emma Baghurst'
theme = 'PaperMod'

[menu]
[[menu.main]]
    identifier = "about"
    name = "About Me"
    url = "/about/"
    weight = 1

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Contact Me"
    url = "/contact/"
    weight = 5

[params]
  defaultTheme = "light"
  disableThemeToggle = true
  comments = true

  [params.assets]
    disableFingerprinting = true
    customCSS = ["css/custom.css"]

  [params.profileMode]
    enabled = true
    title = "Emma Baghurst"
    subtitle = "Software Engineer working in Financial Tech with a background in Medicine."
    imageUrl = "/images/profile.png"
    imageWidth = 270
    imageHeight = 270
    imageTitle = "Emma Baghurst"
    buttons = [
      { name = "Check out my projects!", url = "/projects/" },
    ]

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/em-baggie"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/ebaghurst/"
    

[params.label]
  text = "Emma Baghurst"
  icon = "/img/logo.png"
  iconHeight = 32

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = false
    lineNos = false
    lineNumbersInTable = false

